name: hashicorp/hashicat-aws/infrastructure-tests
on:
  workflow_dispatch: 
  push:
    branches:
      - 'master'
jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Terraform Validate
        run: |-
          terraform init
          terraform validate
permissions:
  contents: read